### ISSUE TITLE
SensorThingAPI python library missing

### ISSUE THREAD

**Issue by mamanso** [AirBreak-UIA/SensorThingsAPI_QGIS-plugin#1]
Dear
I have downloaded and installed as Zip folder complement in QGis and the program show this message: ModuleNotFoundError: No module named 'SensorThingsAPI'

I thing that this module is missing or any information about pre-requisites is needed.

Best

**Comment by AirBreak-UIA** [comment]
Dear Miguel,
to download the correct zip file containing the plugin, you need to:
1. clic on "Actions"
2. clic on "Pack QGIS plugin"
![image](https://user-images.githubusercontent.com/110025591/185896860-5d77a5e5-d37e-4f30-b759-9ad0839951e0.png)

3. download "SensorThingsAPI.1.1.9.zip"
![image](https://user-images.githubusercontent.com/110025591/185897257-f90f6316-ca3d-4c3f-b779-02451d3d1b32.png)
